# Generated by Django 2.2.19 on 2021-04-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210421_1425"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address1", models.CharField(max_length=256)),
                ("address2", models.CharField(blank=True, max_length=256, null=True)),
                ("state", models.CharField(blank=True, max_length=256, null=True)),
                ("city", models.CharField(blank=True, max_length=5, null=True)),
                ("zip", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_location",
                to="users.Location",
            ),
        ),
    ]
